### ISSUE TITLE
Problem on Windows 10 and Devices with HID service

### ISSUE THREAD

**Issue by atc1441** [WebBluetoothCG/registries#24]
Hi am building a website with Web Bluetooth right now.

i have this problem that the device i want to connect to has many Services one of them is The Blocked HID Service. Somehow i am not able to connect to any other Service/Characteristic from that device.

Is that a bug or is it meant to be that way? 

When i browse the same website on my Android Phone via Chrome i can connect to that device and the non blocked Services.

Took a while to get behind this, i am emulating the BLE device with and without the HID Service and when the HID Service is Disabled it does work fine via Chrome on Windows 10

Hope i was clear enough.

Thanks for any Answers

**Comment by odejesush** [comment]
Hi atc1441,

The GATT blocklist is checked in the [requestDevice(options) algorithm](https://webbluetoothcg.github.io/web-bluetooth/#request-bluetooth-devices) a couple of times. The first check is when [canonicalizing the filters](https://webbluetoothcg.github.io/web-bluetooth/#bluetoothlescanfilterinit-canonicalizing). In this algorithm, step 3.4 and 9.5 will reject the promise if the service is blocklisted. Otherwise, the second check occurs in requestDevice(options) step 2.7, and only to remove blocklisted services from options.optionalServices.

Calling BluetoothRemoteGATTServer.connect() should not result in an error due to a blocklisted characteristic.

If a blocklisted GATT child is attempted to be retrieved, the [GetGATTChildren algorithm](https://webbluetoothcg.github.io/web-bluetooth/#getgattchildren) rejects in step 2 if the UUID is in the blocklist.

From a spec point of view, this should not happen. Therefore, this seems like a bug in Chromium's implementation of Web Bluetooth. Please file a bug at https://crbug.com.
